<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>plugin to extend accessory slots, for SamabakeScramble</Description>
        <GameName>SamabakeScramble</GameName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.738"/>
        <PackageReference Include="IllusionLibs.SamabakeScramble.AllPackages" Version="2024.08.30.1"/>
    </ItemGroup>
    <Import Project="../Tasks.xml"/>
</Project>
