<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>plugin to extend accessory slots, for DigitalCraft</Description>
        <GameName>DigitalCraft</GameName>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.752"/>
		<PackageReference Include="BepInEx.KeyboardShortcut.IL2CPP" Version="18.4.1"/>
        <PackageReference Include="IllusionLibs.DigitalCraft.AllPackages" Version="2025.11.21"/>
    </ItemGroup>
    <Import Project="../Tasks.xml"/>
</Project>
